version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    MEDISCAN_ECR_REPO: "615299768302.dkr.ecr.ap-south-1.amazonaws.com/mediscan-app"

phases:
  pre_build:
    commands:
      - set -e # Stop execution on failure

      - echo "🔹 Checking Docker status..."
      - docker info

      - echo "🔹 Logging into AWS ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $MEDISCAN_ECR_REPO

      - echo "🔹 Determining Secrets ARN based on environment..."
      - |
        if [ "$ENVIRONMENT" = "production" ]; then
          SECRET_ARN="arn:aws:secretsmanager:ap-south-1:615299768302:secret:mediscan-app-env-ewBB1v"
        else
          SECRET_ARN="arn:aws:secretsmanager:ap-south-1:615299768302:secret:mediscan-app-env-ewBB1v"
        fi
        echo "Using Secrets ARN: $SECRET_ARN"

      - |
        for VAR in NEXT_PUBLIC_URL NEXT_PUBLIC_APP_VERSION NEXT_PUBLIC_WEB_NAME NEXT_PUBLIC_WEB_MODE  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME NEXT_PUBLIC_CLOUDINARY_API_KEY NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET NEXT_PUBLIC_RAZORPAY_ID; do
        SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $SECRET_ARN --query SecretString --output text)
          export $VAR=$(echo $SECRET_JSON | jq -r .$VAR)
        done

  build:
    commands:
      - set -e # Stop execution on failure

      - echo "🔹 Building Order easy Docker image..."
      - |
        docker build \
          --build-arg NEXT_PUBLIC_URL="$NEXT_PUBLIC_URL" \
          --build-arg NEXT_PUBLIC_APP_VERSION="$TAG_NAME" \
          --build-arg NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME" \
          --build-arg NODE_ENV="$ENVIRONMENT" \
          --build-arg NEXT_PUBLIC_WEB_NAME="$NEXT_PUBLIC_WEB_NAME" \
          --build-arg NEXT_PUBLIC_WEB_MODE="$NEXT_PUBLIC_WEB_MODE" \
          --build-arg NEXT_PUBLIC_CLOUDINARY_API_KEY="$NEXT_PUBLIC_CLOUDINARY_API_KEY" \
          --build-arg NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET="$NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET" \
          --build-arg NEXT_PUBLIC_RAZORPAY_ID="$NEXT_PUBLIC_RAZORPAY_ID" \
          -t $APP_TAG -f ./Dockerfile .

  post_build:
    commands:
      - set -e # Stop execution on failure

      - echo "🔹 Tagging and pushing app image..."
      - docker tag $APP_TAG $MEDISCAN_ECR_REPO:$APP_TAG
      - docker push $MEDISCAN_ECR_REPO:$APP_TAG

artifacts:
  files:
    - imagedefinitions.json

